// <auto-generated />
using System;
using DogBarber.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DogBarber.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DogBarber.Models.Appointment", b =>
                {
                    b.Property<Guid>("GuidID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AppointmentDate");

                    b.Property<string>("AppointmentHour")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("GuidID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DogBarber.Models.User", b =>
                {
                    b.Property<Guid>("GuidID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("GuidID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
